Challenges/9 likes/go/canhassi12
he4rt/he4rtoberfest-2023 pull request #127
Opened 2023-10-04 03:34 UTC by Canhassi12

# [9 - Likes](https://github.com/he4rt/he4rtoberfest-2023/blob/main/challenges/9-likes)

## Explique um pouco como resolveu o desafio

## Pontos interessantes

## Observações

2023-10-04 13:12 UTC, cherryramatisdev requested changes
Me parece que existe um erro de formatação aqui em alguns casos de teste, poderia checar novamente? Abaixo vou mandar os testes

![image](https://github.com/he4rt/he4rtoberfest-2023/assets/86631177/981cda35-a5d8-411d-96b2-5b021d07a00d)

2023-10-04 13:38 UTC, Canhassi12 commented
> Me parece que existe um erro de formatação aqui em alguns casos de teste, poderia checar novamente? Abaixo vou mandar os testes
> 
> ![image](https://user-images.githubusercontent.com/86631177/272585014-981cda35-a5d8-411d-96b2-5b021d07a00d.png)

caraca bugou grandão aslkflkjsd, pode deixar!

2023-10-04 14:46 UTC, gabrielcipriano commented on challenges/9-likes/go/Canhassi12/main.go
> +		fmt.Println(names[0], "curtiu isso")
com o println cada parâmetro fica numa linha... então acho q n vai dar o output esperado

2023-10-04 21:14 UTC, Canhassi12 commented on challenges/9-likes/go/Canhassi12/main.go
> +		fmt.Println(names[0], "curtiu isso")
Humm, pior que eu testei aqui e funcionou kkkkk, da uma olhadinha e vê o que acha.

![image](https://github.com/he4rt/he4rtoberfest-2023/assets/80018897/e197254a-eb0b-4814-99a1-567e8774982b)

2023-10-05 21:16 UTC, lanjoni requested changes
Muito obrigado pela PR! Só um problema: a entrada está sendo feita utilizando mais de um argumento! A entrada deve conter apenas um argumento e depois deve ser realizado o parse dessa entrada, removendo os colchetes ('[' e ']'), e depois dividir e quebrar as vírgulas para que possa cada um dos valores ser uma posição dentro de um array novo. Acredito que esta seja a forma mais simples, assim você conta a quantidade de itens no array e em um simples `case` consegue validar!

2023-10-05 21:35 UTC, gabrielcipriano commented on challenges/9-likes/go/Canhassi12/main.go
> +		fmt.Println(names[0], "curtiu isso")
que curioso hahahha tudo certo entao

2023-10-24 00:42 UTC, lanjoni approved these changes

2023-10-24 00:42 UTC, merged