Finalizando o desafio 1
he4rt/he4rtoberfest-2023 pull request #20
Opened 2023-10-03 04:18 UTC by Sherlockzen

# 1 Challenge

## Explique um pouco como resolveu o desafio
Criei uma função que receba um número inteiro e me retorne o cubo deste número.
Depois na função main implementei a leitura de um valor digitado pelo usuário que é usado como argumento da função que me retorna o cubo, o retorno dessa função atribuo a uma variável e imprimo ela na tela.

## Pontos interessantes
A **func main()** de um projeto Go não pode receber argumentos ou retornar valores.

## Observações

2023-10-03 10:13 UTC, lanjoni requested changes
Maravilha! Muito obrigado pela PR!

Bem, vi que você enviou dois exercícios em uma PR só, por agora tudo ok, mas, nas próximas por favor, envie um exercício por PR.

Por favor, também considere apagar o `go.mod`, tendo em vista que só é necessário o arquivo com extensão `.go`.

2023-10-03 11:34 UTC, midhatdrops requested changes
@Sherlockzen Não é exatamente um problema.  Mas vc poderia usar a lib de math(math.pow()) para elevar ao cubo ao invés de criar uma função própria.

Único ponto de correção, seguindo o criterio de legibilidade, é alterar o nome da função square para cube, pois ela não está elevando o número ao quadrado e sim ao cubo.

2023-10-04 00:51 UTC, Sherlockzen commented
> Maravilha! Muito obrigado pela PR!
> 
> Bem, vi que você enviou dois exercícios em uma PR só, por agora tudo ok, mas, nas próximas por favor, envie um exercício por PR.
> 
> Por favor, também considere apagar o `go.mod`, tendo em vista que só é necessário o arquivo com extensão `.go`.

Puts, que vacilo, vou corrigir isso e as outras coisas

2023-10-04 00:52 UTC, Sherlockzen commented
> @Sherlockzen Não é exatamente um problema. Mas vc poderia usar a lib de math(math.pow()) para elevar ao cubo ao invés de criar uma função própria.
> 
> Único ponto de correção, seguindo o criterio de legibilidade, é alterar o nome da função square para cube, pois ela não está elevando o número ao quadrado e sim ao cubo.

Sim sim, corretíssimo, eu li cubo, mas fiz pensando que era ao quadrado kkkkkkk

2023-10-04 21:47 UTC, Canhassi12 commented
Boa noite, se possivel apague o arquivo go.mod por favor. E lembre-se de criar novas branchs a partir da main para não enviar todos os exercicios nas PRs futuras.

2023-10-04 22:18 UTC, Sherlockzen commented
> Boa noite, se possivel apague o arquivo go.mod por favor. E lembre-se de criar novas branchs a partir da main para não enviar todos os exercicios nas PRs futuras.

Caramba é o Canhas, vou fazer essas correções.

2023-10-13 02:09 UTC, closed without merging