Finalizando desafio 9
he4rt/he4rtoberfest-2023 pull request #348
Opened 2023-10-06 21:27 UTC by dscamargo

# Challenge 9 - Likes

## Explique um pouco como resolveu o desafio
Após receber os argumentos via `ARGV` foi utilizado case/when para tratar o output de acordo com o tamanho da lista de nomes.

## Pontos interessantes

## Observações

2023-10-10 15:48 UTC, k8adev commented
@dscamargo está com um problema no output, consegue conferir e mandar uma correção? 🙏🏻

<img width="1871" alt="Screenshot 2023-10-10 at 12 47 28" src="https://github.com/he4rt/he4rtoberfest-2023/assets/3808430/c1b150c3-e449-4045-af2e-73f29b3b0adb">

2023-10-10 17:10 UTC, dscamargo commented
> @dscamargo está com um problema no output, consegue conferir e mandar uma correção? 🙏🏻
> <img alt="Screenshot 2023-10-10 at 12 47 28" width="1871" src="https://user-images.githubusercontent.com/3808430/273976112-c1b150c3-e449-4045-af2e-73f29b3b0adb.png">

Feito !

2023-10-10 17:22 UTC, k8adev requested changes
@dscamargo só o Dani curtiu isso 😭

<img width="1670" alt="Screenshot 2023-10-10 at 14 22 05" src="https://github.com/he4rt/he4rtoberfest-2023/assets/3808430/1ecc0c0b-7537-4e3c-bb43-d83454144523">

2023-10-13 02:10 UTC, lanjoni approved these changes

2023-10-13 02:11 UTC, merged