feat: hello world csharp
he4rt/he4rtoberfest-2023 pull request #54
Opened 2023-10-03 17:58 UTC by BrunaGPires

# (0) Challenge
Challenge 0 - Hello World

## Explique um pouco como resolveu o desafio

## Pontos interessantes

## Observações

2023-10-03 18:52 UTC, Canhassi12 commented
Olá. peço que remova algumas pastas, como ```obj```, ```bin``` e ```vscode```.  ou apenas coloque no .gitignore. Ai o projeto ficaria só com o arquivo ```.cs```, ```.csproj``` e o readme.

2023-10-03 18:54 UTC, lanjoni requested changes
Muito obrigado pela PR! Poderia por favor deixar apenas o arquivo `.cs` e `.csproj`? Veio o projeto completo!

PS: Valeu Canhas, não tinha visto seu comentário ainda...

2023-10-03 21:29 UTC, BrunaGPires commented
Olá, concluí as modificações solicitadas.

2023-10-03 22:25 UTC, Canhassi12 commented
Acho que você pode apagar o ```.sln``` também, ele só funciona para as configs do editor.

2023-10-03 22:49 UTC, lanjoni requested changes
Poderia só remover o arquivo `.sln` por favor?

2023-10-04 00:02 UTC, Canhassi12 approved these changes

2023-10-04 00:03 UTC, merged