Finalizando o desafio 6 - php
he4rt/he4rtoberfest-2023 pull request #76
Opened 2023-10-03 21:36 UTC by gdiasb

# (Número do desafio) Challenge 6 - Números Primos

## Explique um pouco como resolveu o desafio
Criação do arquivo primo.php, que aplica uma verificação nas condições para dizer se um número é primo ou não. Execução no terminal.

## Pontos interessantes

## Observações

2023-10-03 21:57 UTC, lanjoni requested changes
Alguns problemas de validação que encontrei para o número `3` e o número `1000` por exemplo. Uma sugestão seria realizar um contador começando do número 2:

```php
$i = 2;
while($i < $numero){
    if (($numero % i) == 0){
        return false;
    }
    
    $i += 1;
}

return true;
```

<img width="178" alt="image" src="https://github.com/he4rt/he4rtoberfest-2023/assets/91899995/621c29a6-893b-495d-94ce-6bb28a56e8d9">

2023-10-03 22:09 UTC, gdiasb commented
Corrigi!

2023-10-03 22:30 UTC, lanjoni commented on challenges/6-numeros-primos/php/gdiasb/primos.php
> +    }
Aqui vai uma sugestão que deve funcionar! Alguns números estavam com problemas, mas, ao invés de apenas responder que estava com problema resolvi te dar uma ideia do que fazer.

Nesse laço teoricamente você *não pode* retornar com um else dentro, porque senão sempre ele vai cair no else e retornar algo, independente de qual passo você estiver (utilize uma ferramenta de debug que você vai ver, sempre vai no else), assim, o `return 'true'` deve estar por fora.

Deixando por fora, sempre vai retornar `'false'`, porque no seu laço estava contabilizando o passo como `<=`, sendo que quando eles são iguais realmente eles são divisíveis (como 7, no passo 7/7 tem resto 0, afinal, números primos são divisíveis por 1 e por eles mesmos apenas).

Acredito que isso deve solucionar o problema e espero que tenha esclarecido e te auxiliado!

```suggestion
    for ($i = 2; $i < $num; $i++)
    {
        if ($num % $i == 0)
        {
            return 'false';
        }
    }
    return 'true';
```

2023-10-03 22:30 UTC, lanjoni requested changes
Por favor, valide se meu comentário anterior fez sentido!

2023-10-03 23:46 UTC, gdiasb reviewed
Opa agora que vi de novo as requests

2023-10-03 23:56 UTC, gdiasb commented
Muito obrigada Guto pelos alertas!

2023-10-04 00:04 UTC, lanjoni commented
Eu quem agradeço! Fico feliz que tenha dado certo!

2023-10-04 00:04 UTC, merged