Challenge/4 emprestimo/rust/wellers0n
he4rt/he4rtoberfest-2023 pull request #97
Opened 2023-10-04 00:23 UTC by Wellers0n

# Challenge 4-emprestimo

## Explique um pouco como resolveu o desafio

Bem simples, recebo 3 input como argumento e faço o calculo com base no desafio!

## Pontos interessantes

## Observações

2023-10-04 23:13 UTC, lanjoni requested changes
Muito obrigado pela PR! Os testes estão passando normalmente, porém, precisamos que você envie apenas o `README.md` e o `main.rs`, nada além disso! Para testar estamos utilizando o próprio `rustc` para gerar o executável, por isso, não estamos aceitando nenhum outro arquivo adicional de nenhuma linguagem de programação que não seja a resolução e o `README.md`!

2023-10-04 23:55 UTC, Wellers0n commented
> Muito obrigado pela PR! Os testes estão passando normalmente, porém, precisamos que você envie apenas o `README.md` e o `main.rs`, nada além disso! Para testar estamos utilizando o próprio `rustc` para gerar o executável, por isso, não estamos aceitando nenhum outro arquivo adicional de nenhuma linguagem de programação que não seja a resolução e o `README.md`!

Opa, acabei de ajeitar esses pontos

2023-10-04 23:59 UTC, Wellers0n commented
> Salve @Wellers0n, você esqueceu de mandar o desafio 0!

hello world

https://github.com/he4rt/he4rtoberfest-2023/pull/219

2023-10-05 21:24 UTC, lanjoni approved these changes

2023-10-05 21:25 UTC, merged